version: "3.9"


services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-abhishek}"
    image: cybulde-model
    platform: linux/amd64
    container_name: cybulde-model-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-abhi}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-abhi}/.config/gcloud
    ports:
      - 8080:8080

    ipc: host
    init: true


